### ISSUE TITLE
change week number to date range?

### ISSUE THREAD

**Issue by samabsalom** [olejon/phpmyreservation#20]
Tried looking at how to change the booking form top from 'Reservations for week 19' to 'Reservations for 9/5/16 - 15/5/16' for example. Sadly can't work it out and some help would be greatly appreciated ! Thanks, Sam

**Comment by olejon** [comment]
You can check out this:

http://stackoverflow.com/questions/186431/calculating-days-of-week-given-a-week-number

...or this:

http://stackoverflow.com/questions/4861384/php-get-start-and-end-date-of-a-week-by-weeknumber

...and just modify the code.

I will release v 1.1 soon. Nothing really new, just support for timezone for all users, so that if the server is located in another timezone than the users, it will work. And some design changes and code improvements.
